# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alessandro Vioni
tagline:          "front end developer"
description:      "Front end developer born some forty years ago in Italy"
url:              http://www.alessandrovioni.com

author:
  name:           'Alessandro Vioni'
  url:            https://twitter.com/jenoma

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/genoma
